# Generated by Django 4.1.4 on 2022-12-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='ownername',
            new_name='name',
        ),
    ]
