# Generated by Django 4.1.4 on 2022-12-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_rename_ownername_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
