# Generated by Django 4.1.4 on 2022-12-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_home_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='parking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='swimming_pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
