# Generated by Django 4.1.4 on 2022-12-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_home_parking_home_swimming_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='homespecified',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
