# Generated by Django 4.1.4 on 2022-12-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_homespecified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homespecified',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
