# Generated by Django 4.1.4 on 2022-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_homespecified_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homespecified',
            name='date',
        ),
        migrations.RemoveField(
            model_name='homespecified',
            name='time',
        ),
        migrations.AddField(
            model_name='homespecified',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
